# Generated by Django 4.2 on 2023-05-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=20)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_email', models.CharField(max_length=20)),
                ('guest_address', models.CharField(max_length=20)),
                ('guest_gender', models.CharField(max_length=10)),
                ('guest_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_description', models.CharField(default='A nice and comfortable room for you stay', max_length=500)),
                ('room_type', models.CharField(max_length=10)),
                ('room_count', models.IntegerField(default=0)),
                ('room_price', models.IntegerField()),
                ('room_booked_count', models.IntegerField(default=0)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.IntegerField(default=1)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField(null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.room')),
            ],
        ),
    ]
