# Generated by Django 4.2 on 2023-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_type',
            field=models.CharField(choices=[('Official guest', 'Official guest'), ('Staff guest', 'Staff guest'), ('Normal guest', 'Normal guest')], default='Normal guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC single', 'AC single'), ('Ac double', 'Ac double'), ('AC semi suit', 'AC semi suit'), ('AC suit', 'AC suit'), ('Conference Room', 'Conference Room'), ('Party/Dining Hall with catering', 'Party/Dining Hall with catering'), ('Party/Dining Hall without catering', 'Party/Dining Hall without catering')], default='AC single', max_length=50),
        ),
    ]
