# Generated by Django 4.2 on 2023-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_remove_room_room_price_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC single', 'AC single'), ('AC double', 'Ac double'), ('AC semi suit', 'AC semi suit'), ('AC suit', 'AC suit'), ('Conference Room', 'Conference Room'), ('Party/Dining Hall with catering', 'Party/Dining Hall with catering'), ('Party/Dining Hall without catering', 'Party/Dining Hall without catering')], default='AC single', max_length=50),
        ),
    ]
